// Graph presets and helper structures for BFS & DFS

export const GRAPH_PRESETS = {
  tree: {
    name: "Binary/Hierarchical Tree",
    nodes: [
      { id: "A", label: "A", x: 300, y: 50 },
      { id: "B", label: "B", x: 160, y: 140 },
      { id: "C", label: "C", x: 440, y: 140 },
      { id: "D", label: "D", x: 90,  y: 240 },
      { id: "E", label: "E", x: 230, y: 240 },
      { id: "F", label: "F", x: 370, y: 240 },
      { id: "G", label: "G", x: 510, y: 240 },
    ],
    edges: [
      { from: "A", to: "B" },
      { from: "A", to: "C" },
      { from: "B", to: "D" },
      { from: "B", to: "E" },
      { from: "C", to: "F" },
      { from: "C", to: "G" },
    ],
    adj: {
      A: ["B", "C"],
      B: ["A", "D", "E"],
      C: ["A", "F", "G"],
      D: ["B"],
      E: ["B"],
      F: ["C"],
      G: ["C"],
    },
    defaultStart: "A",
  },
  cyclic: {
    name: "Network with Cycles",
    nodes: [
      { id: "A", label: "A", x: 180, y: 60 },
      { id: "B", label: "B", x: 420, y: 60 },
      { id: "C", label: "C", x: 520, y: 180 },
      { id: "D", label: "D", x: 420, y: 290 },
      { id: "E", label: "E", x: 180, y: 290 },
      { id: "F", label: "F", x: 80,  y: 180 },
      { id: "G", label: "G", x: 300, y: 175 },
    ],
    edges: [
      { from: "A", to: "B" },
      { from: "B", to: "C" },
      { from: "C", to: "D" },
      { from: "D", to: "E" },
      { from: "E", to: "F" },
      { from: "F", to: "A" },
      { from: "A", to: "G" },
      { from: "B", to: "G" },
      { from: "D", to: "G" },
    ],
    adj: {
      A: ["B", "F", "G"],
      B: ["A", "C", "G"],
      C: ["B", "D"],
      D: ["C", "E", "G"],
      E: ["D", "F"],
      F: ["E", "A"],
      G: ["A", "B", "D"],
    },
    defaultStart: "A",
  },
  dag: {
    name: "Complex Web (8 Nodes)",
    nodes: [
      { id: "0", label: "0", x: 100, y: 80 },
      { id: "1", label: "1", x: 260, y: 60 },
      { id: "2", label: "2", x: 420, y: 80 },
      { id: "3", label: "3", x: 520, y: 200 },
      { id: "4", label: "4", x: 420, y: 310 },
      { id: "5", label: "5", x: 260, y: 330 },
      { id: "6", label: "6", x: 100, y: 310 },
      { id: "7", label: "7", x: 260, y: 190 },
    ],
    edges: [
      { from: "0", to: "1" },
      { from: "0", to: "6" },
      { from: "1", to: "2" },
      { from: "1", to: "7" },
      { from: "2", to: "3" },
      { from: "2", to: "7" },
      { from: "3", to: "4" },
      { from: "4", to: "5" },
      { from: "4", to: "7" },
      { from: "5", to: "6" },
      { from: "6", to: "7" },
    ],
    adj: {
      "0": ["1", "6"],
      "1": ["0", "2", "7"],
      "2": ["1", "3", "7"],
      "3": ["2", "4"],
      "4": ["3", "5", "7"],
      "5": ["4", "6"],
      "6": ["0", "5", "7"],
      "7": ["1", "2", "4", "6"],
    },
    defaultStart: "0",
  }
};
